package api

import (
	"context"

	"github.com/mstilde/unipile-linkedin-go/internal/db/gen"
)

// SQLAccountStore implements auth.AccountOwnershipStore against the gen.Queries
// generated by sqlc.
type SQLAccountStore struct {
	Q *gen.Queries
}

func (s *SQLAccountStore) UserOwnsAccount(ctx context.Context, userID int64, accountID string) (bool, error) {
	owned, err := s.Q.IsAccountOwned(ctx, gen.IsAccountOwnedParams{
		ID:          accountID,
		OwnerUserID: &userID,
	})
	if err != nil {
		return false, err
	}
	return owned, nil
}
